version: '2'

services:
  postgres-db:
    image: 'postgres:latest'
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airport